name = "Idiotic Aeronauts"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e098bb9679027edea9de1868bc94f017445bed1c79e1b7d1f310beab5ed1030"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
