name = "Idiotic Aeronauts"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7344d5372074de665f5dcf2cb2fee3c5cb426bd8b464a38eb8b6aa6b10abd80"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
